### ISSUE TITLE
Execute simpleindex from another Python module

### ISSUE THREAD

**Issue by tibortakacs** [uranusjr/simpleindex#11]
At the moment, `simpleindex` can be executed only as `python -m simpleindex ...`. It would be beneficial to embedded simpleindex into another Python application as a simple module.

**Comment by tibortakacs** [comment]
@uranusjr This would be an important use case for my tooling application. Here is the PR for that: https://github.com/uranusjr/simpleindex/pull/12

What do you think? Looking forward to your opinion.

**Comment by uranusjr** [comment]
Published 0.5.0 for this.
