### ISSUE TITLE
Enable streaming response from custom routes

### ISSUE THREAD

**Issue by tibortakacs** [uranusjr/simpleindex#5]
In the current implementation, the `Route` object `get_page` and `get_file` functions returns an internal `Response` data object that are translated into `starlette` `Response` object. This makes not possible to return different response types like streaming responses from the custom routes. Returning `startlette.StreamingResponse` would be great to have by downloading large packages.

**Comment by tibortakacs** [comment]
I am forking and creating a draft PR to show a possible solution.

**Comment by tibortakacs** [comment]
There are two design directions:
* https://github.com/uranusjr/simpleindex/pull/6 -> This is about bypassing `starlette.Response` objects. This gives more flexibility to the custom routes, but it bind `simpleindex` to `starlette` (which is either bad or a good thing).
* https://github.com/uranusjr/simpleindex/pull/7 -> This is solution extend the `Response` data object with a `streaming` flag, and based on this flag, different `starlette` response object is created.
* (I can see other approaches like creating a `routes.StreamingResponse` data object.)

I am looking forward to your opinion.

**Comment by uranusjr** [comment]
I want to keep Starlette an implementation detail. If we expose its Response class directly, custom route types would not work if we chang ethe implementation. Instead of adding a `streaming` attribute, perhaps it would be equally good to add a subclass StreamingResponse to match Starlette’s interface. We can also abstract the conversion away in a `to_http_response` on the Response/StreamingResponse classes.

**Comment by tibortakacs** [comment]
Thank you, this sounds great. I have been thinking about this, and adding the `StreamingResponse` class could be a more flexible option. Although my draft PR above added the `streaming` flag, this would many that the `Response` class could be too complex in the future if more flags are added. Instead,  having separate class for each use cases (similarly to Starlette) could be more future proof solution. But I am happy with either way.

I will implement the draft for the new StreamingResponse class, and you can decide which is the best for the repo.

**Comment by tibortakacs** [comment]
@uranusjr Please find the corresponding PR here: https://github.com/uranusjr/simpleindex/pull/8
(I have fixed the existing unit tests, and add a basic one for the type conversion. This latter one could be improved once we have a testing framework in place for the route testing.)

**Comment by tibortakacs** [comment]
@uranusjr Thank you for merging the PR in. Do you think we can have a new release with it soon?

**Comment by uranusjr** [comment]
Doing it now.
